In [1]:
# Dependencies
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import numpy as np
import seaborn as sns
import os 
from generateXdata import generateX

# Load in csv

#raw_df = pd.read_csv("C:/Users/admin/Documents/SMU/Final Project/Data/recs2015.csv")
filepath = os.path.join("dataforfinalproject","RECS_COMBINED_DATA.csv")
raw_df=pd.read_csv(filepath)
colmns_file = os.path.join("dataforfinalproject","Final_Columns_withCat.csv")
cols_file=pd.read_csv(colmns_file)

In [ ]:
# read the columns from Columns csv
df_cols = pd.read_csv(colmns_file)
df_cols
# df_cols.columns

In [3]:
raw_df.describe()

,RECSYEAR,DOEID,REGIONC,DIVISION,TYPEHUQ,CELLAR,STORIES,PRKGPLC1,YEARMADE,OCCUPYY,...,WDPELLET,WDOTHER,WDWARM,WDWATER,USESOLAR,SOLWATER,SOLOTHER,TVAUDIOEQUIP,PCOFFEQUIP,PHONE
count,22591.000000,22591.000000,22591.000000,22591.000000,22591.000000,22591.000000,22591.000000,22591.000000,22591.000000,22591.000000,...,22591.000000,22591.000000,22591.000000,22591.000000,22591.000000,22591.000000,22591.000000,22591.000000,22591.000000,22591.000000
mean,2008.802576,7195.131247,2.651498,5.382453,2.638484,0.143199,15.248373,0.475897,4.050640,6.796069,...,0.255544,-1.387411,0.114824,0.001284,0.010579,0.002523,0.006994,6.695720,2.764110,1.534107
std,4.762735,4402.416131,1.045644,2.821670,1.184945,2.250864,20.100299,2.239042,2.246379,1.992055,...,4.179991,0.927600,0.318817,0.035807,0.102313,0.050168,0.083339,3.735064,2.343253,1.120486
min,2001.000000,1.000000,1.000000,1.000000,1.000000,-2.000000,-2.000000,-2.000000,1.000000,1.000000,...,-2.000000,-2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2009.000000,3330.000000,2.000000,3.000000,2.000000,-2.000000,10.000000,0.000000,2.000000,6.000000,...,-2.000000,-2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,1.000000,1.000000
50%,2009.000000,6474.000000,3.000000,5.000000,2.000000,0.000000,10.000000,0.000000,4.000000,7.000000,...,-2.000000,-2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,3.000000,2.000000
75%,2015.000000,11061.000000,3.000000,7.000000,3.000000,1.000000,20.000000,1.000000,6.000000,8.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,4.000000,2.000000
max,2015.000000,15686.000000,4.000000,10.000000,5.000000,9.000000,99.000000,9.000000,13.000000,9.000000,...,9.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,43.000000,23.000000,10.000000

In [ ]:
#from sklearn.preprocessing import StandardScaler
#features =raw_df[[']]

# Data Preparation

In [6]:
# Extract features and labels
labels = raw_df['TOTALBTU']
#labels = raw_df['TOTALDOLLAR']
#raw_df = features.drop('TYPEHUQ', axis = 1)

In [7]:
# List of features for later use

modelDF = df_cols[df_cols.FEATURES_MODEL == "Y"].COLUMN_NAME
features=modelDF
#print(modelDF)
#feature = list(features.columns)

In [8]:
# Convert to numpy array
features = generateX()

 X Features shape : (22591, 87)
y label shape : (22591,)
cols with values as 99 and -2: ['CELLAR', 'STORIES', 'PRKGPLC1', 'BEDROOMS', 'FUELPOOL', 'SIZRFRI1', 'TYPERFR1', 'AGERFRI1', 'SIZRFRI2', 'TYPERFR2', 'AGERFRI2', 'NUMFREEZ', 'SIZFREEZ', 'AGEFRZR', 'STOVENFUEL', 'OVENUSE', 'AMTMICRO', 'DWASHUSE', 'WASHLOAD', 'WASHTEMP', 'EQUIPM', 'FUELHEAT', 'EQUIPAGE', 'PROTHERM', 'TEMPHOME', 'TEMPGONE', 'TEMPNITE', 'AGECENAC', 'USECENAC', 'NUMBERAC', 'WWACAGE', 'USEWWAC', 'FUELH2O', 'WHEATAGE', 'WHEATSIZ', 'LGTOUTNUM', 'ESDISHW', 'PGASHEAT', 'WOODAMT']

Duplicate Count : 0
(22591, 80)
shape of X is (22591, 79)

In [ ]:
g = sns.pairplot(raw_df,
x_vars=["TOTALBTU", "TOTALDOL"],
y_vars=["BTUNG", 'BTUELAHUHEAT','BTUEL','DOLLAREL', 'CUFEETNG','GALLONFO','BTUFO','GALLONLP','BTULP','DOLLARFO'])

In [10]:
# Using Skicit-learn to split data ihttp://localhost:8888/notebooks/Documents/SMU/Project3final/ConsRandForest.ipynb#nto training and testing sets
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25, random_state = 42)

In [11]:
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)

Training Features Shape: (16943, 79)
Training Labels Shape: (16943,)
Testing Features Shape: (5648, 79)
Testing Labels Shape: (5648,)

In [ ]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor

# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)

# Train the model on training data
rf.fit(train_features, train_labels);

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

In [ ]:
# Random Forests in sklearn will automatically calculate feature importance
importances = rf.feature_importances_
importances

In [ ]:
# We can sort the features by their importance
sorted(zip(rf.feature_importances_,features), reverse=True)

In [ ]:
# Use the forest's predict method on the test data
predictions = rf.predict(test_features)

# Calculate the absolute errors
errors = abs(predictions - test_labels)

# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

In [ ]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / test_labels)

# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')