In [1]:
# Dependencies
import matplotlib.pyplot as plt

%matplotlib inline
import pandas as pd
import numpy as np
import seaborn as sns
import os 
from generateXdata import generateX
from math import ceil
import warnings
# Load in csv

#raw_df = pd.read_csv("C:/Users/admin/Documents/SMU/Final Project/Data/recs2015.csv")
filepath = os.path.join("dataforfinalproject","RECS_COMBINED_DATA.csv")
raw_df=pd.read_csv(filepath)
colmns_file = os.path.join("dataforfinalproject","Final_Columns_withCat.csv")
cols_file=pd.read_csv(colmns_file)

In [2]:
# read the columns from Columns csv
df_cols = pd.read_csv(colmns_file)
df_cols
# df_cols.columns

,COLUMN_NAME,COLUMN_CAT_ABBR,COLUMN_CATEGORY,COLUMN_DESCRIPTION,FEATURES_MODEL,COLUMN_TYPE,REQ_ONEHOTENC
0,RECSYEAR,COMMON,CommonVariables,Survey Conducted Year,N,Numerical,False
1,COUNTRY,COMMON,CommonVariables,String,N,String,False
2,DOEID,COMMON,CommonVariables,4-digit identification number,N,Numerical,False
3,REGIONC,COMMON,CommonVariables,Census Region,Y,Categorical,True
4,REGIONNAME,COMMON,CommonVariables,Region Name,N,Categorical,True
5,DIVISION,COMMON,CommonVariables,Census Division,Y,Categorical,True
6,DIVISIONNAME,COMMON,CommonVariables,Division names,N,Categorical,True
7,TYPEHUQ,COMMON,CommonVariables,Type of Home: as report by Respondent,N,Categorical,True
8,CELLAR,HUC,Housing Unit Characteristics,Home Has Basement,Y,Categorical,True
9,STORIES,HUC,Housing Unit Characteristics,Reported Stories in Housing Unit,Y,Numerical,False
10,PRKGPLC1,HUC,Housing Unit Characteristics,Home has Garage or Carport,Y,Categorical,True
11,YEARMADE,HUC,Housing Unit Characteristics,Year Home Built,Y,Categorical,True
12,OCCUPYY,HUC,Housing Unit Characteristics,Year Moved into Home,Y,Categorical,True
13,BEDROOMS,HUC,Housing Unit Characteristics,Number of bedrooms,Y,Numerical,False
14,NCOMBATH,HUC,Housing Unit Characteristics,Number of Complete Baths,Y,Numerical,False
15,NHAFBATH,HUC,Housing Unit Characteristics,Number of Half Baths,Y,Numerical,False
16,OTHROOMS,HUC,Housing Unit Characteristics,Number of Other Rooms,Y,Numerical,False
17,TOTROOMS,HUC,Housing Unit Characteristics,Total Number of Rooms,Y,Numerical,False
18,DOOR1SUM,WTH,"Water heating, Cooling and Miscell",Number of sliding glass doors,N,Numerical,False
19,WINDOWS,WTH,"Water heating, Cooling and Miscell",Number of windows,Y,Categorical,True
20,ADQINSUL,WTH,"Water heating, Cooling and Miscell",Respondent perception of home insulation,Y,Categorical,True
21,DRAFTY,WTH,"Water heating, Cooling and Miscell",How often find your home too drafty during winter,Y,Categorical,True
22,UGASHERE,HUC,Housing Unit Characteristics,Natural gas from underground pipe available,N,Categorical,True
23,FUELPOOL,APL_OTH,Other Appliances,What fuel is used most often to heat pool water,Y,Categorical,True
24,SIZRFRI1,APL_KIT,Kitchen Appliances,Size of first refrigerator,Y,Categorical,True
25,TYPERFR1,APL_KIT,Kitchen Appliances,Type of first refrigerators,Y,Categorical,True
26,AGERFRI1,APL_KIT,Kitchen Appliances,How old is first refrigerator,Y,Categorical,True
27,ICE,APL_KIT,Kitchen Appliances,Does refrigerator have through-the-door ice,N,Categorical,True
28,SIZRFRI2,APL_KIT,Kitchen Appliances,Size of second refrigerator,Y,Categorical,True
29,TYPERFR2,APL_KIT,Kitchen Appliances,Type of second refrigerator,Y,Categorical,True
...,...,...,...,...,...,...,...
172,AIRCOND,WTH,"Water heating, Cooling and Miscell",Do you have air conditioning equipment at home,N,Categorical,True
173,CENACHP,WTH,"Water heating, Cooling and Miscell",Is your central AC system a heat pump,N,Categorical,True
174,USEEL,FUP,Fuels Used and Fuel Payment,HH uses electricity,N,Categorical,True
175,ELWARM,FUP,Fuels Used and Fuel Payment,Electricity used for heat,N,Categorical,True
176,ELCOOL,FUP,Fuels Used and Fuel Payment,Electricity used to cool,N,Categorical,True
177,ELFOOD,FUP,Fuels Used and Fuel Payment,Electricity used to cook,N,Categorical,True
178,ELOTHER,FUP,Fuels Used and Fuel Payment,Electricity used for other,N,Categorical,True
179,UGWARM,FUP,Fuels Used and Fuel Payment,Natural gas used for heat,N,Categorical,True
180,UGWATER,FUP,Fuels Used and Fuel Payment,Natural gas used for H2O,N,Categorical,True
181,UGCOOK,FUP,Fuels Used and Fuel Payment,Natural gas used to cook,N,Categorical,True
182,UGOTH,FUP,Fuels Used and Fuel Payment,Natural gas used for other,N,Categorical,True
183,USELP,FUP,Fuels Used and Fuel Payment,HH uses LPG,N,Categorical,True
184,LPWARM,FUP,Fuels Used and Fuel Payment,Bottled gas used for heat,N,Categorical,True
185,LPWATER,FUP,Fuels Used and Fuel Payment,Bottled gas used for H2O,Y,Categorical,True
186,LPCOOK,FUP,Fuels Used and Fuel Payment,Bottled gas used to cook,N,Categorical,True
187,USEFO,FUP,Fuels Used and Fuel Payment,HH uses Fuel oil,N,Categorical,True
188,FOWARM,FUP,Fuels Used and Fuel Payment,Fuel oil used for heat,N,Categorical,True
189,FOWATER,FUP,Fuels Used and Fuel Payment,Fuel oil used for H2O,N,Categorical,True
190,USEWOOD,FUP,Fuels Used and Fuel Payment,HH uses Wood,N,Categorical,True
191,WOODLOGS,FUP,Fuels Used and Fuel Payment,Use Wood logs or split wood as a fuel in house,N,Categorical,True
192,WDPELLET,FUP,Fuels Used and Fuel Payment,Use Wood pellets as a fuel in house,N,Categorical,True
193,WDOTHER,FUP,Fuels Used and Fuel Payment,Wood used for other,N,Categorical,True
194,WDWARM,FUP,Fuels Used and Fuel Payment,Wood used for heat,N,Categorical,True
195,WDWATER,FUP,Fuels Used and Fuel Payment,Wood used for H2O,N,Categorical,True
196,USESOLAR,FUP,Fuels Used and Fuel Payment,HH uses solar,N,Categorical,True
197,SOLWATER,FUP,Fuels Used and Fuel Payment,Solar used for H2O,N,Categorical,True
198,SOLOTHER,FUP,Fuels Used and Fuel Payment,Solar used for other,N,Categorical,True
199,TVAUDIOEQUIP,APL_OTH,Other Appliances,"Total of All TV, Audio, Stereo, VCR, DVD etc.,",Y,Numerical,False
200,PCOFFEQUIP,APL_OTH,Other Appliances,"Total of Desktop, laptop, printer, fax, copier...",Y,Numerical,False
201,PHONE,APL_OTH,Other Appliances,Total of all phones including smartphone and r...,Y,Numerical,False

In [3]:
raw_df.describe()

,RECSYEAR,DOEID,REGIONC,DIVISION,TYPEHUQ,CELLAR,STORIES,PRKGPLC1,YEARMADE,OCCUPYY,...,WDPELLET,WDOTHER,WDWARM,WDWATER,USESOLAR,SOLWATER,SOLOTHER,TVAUDIOEQUIP,PCOFFEQUIP,PHONE
count,21430.000000,21430.000000,21430.000000,21430.000000,21430.000000,21430.000000,21430.000000,21430.000000,21430.000000,21430.000000,...,21430.000000,21430.000000,21430.000000,21430.000000,21430.000000,21430.000000,21430.000000,21430.000000,21430.000000,21430.000000
mean,2008.789827,7205.857863,2.679888,5.453010,2.666636,0.126832,15.122912,0.468735,4.062529,6.808166,...,0.295194,-1.385768,0.112179,0.001260,0.009846,0.002427,0.006300,6.524078,2.665982,1.516472
std,4.803271,4406.168345,1.035783,2.806848,1.205252,2.300688,20.558255,2.286153,2.237875,2.003827,...,4.218022,0.927989,0.315594,0.035474,0.098740,0.049201,0.079121,3.612805,2.276647,1.118314
min,2001.000000,1.000000,1.000000,1.000000,1.000000,-2.000000,-2.000000,-2.000000,1.000000,1.000000,...,-2.000000,-2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2009.000000,3336.250000,2.000000,3.000000,2.000000,-2.000000,10.000000,0.000000,2.000000,6.000000,...,-2.000000,-2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,1.000000,1.000000
50%,2009.000000,6481.500000,3.000000,5.000000,2.000000,0.000000,10.000000,0.000000,4.000000,8.000000,...,-2.000000,-2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,3.000000,2.000000
75%,2015.000000,11072.750000,4.000000,8.000000,3.000000,1.000000,20.000000,1.000000,6.000000,8.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,4.000000,2.000000
max,2015.000000,15686.000000,4.000000,10.000000,5.000000,9.000000,99.000000,9.000000,13.000000,9.000000,...,9.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,33.000000,23.000000,10.000000

In [4]:
#from sklearn.preprocessing import StandardScaler
#features =raw_df[[']]

# Data Preparation

In [3]:
# Extract features and labels
labels = raw_df['TOTALDOLLAR']
#raw_df = features.drop('TYPEHUQ', axis = 1)

In [4]:
# List of features for later use

#model = df_cols[df_cols.FEATURES_MODEL == "Y"].COLUMN_NAME
#modelDF=model.drop(columns=['TOTALBTU'])

#feature=modelDF
#print(modelDF)
#features = list(features.columns)

In [5]:
# Gathering features and columns
features_X,columns_names = generateX(ohe = True, target = "DOLLAR")

 X Features shape : (21430, 87)
y label shape : (21430,)
cols with values as 99 and -2: ['CELLAR', 'STORIES', 'PRKGPLC1', 'BEDROOMS', 'FUELPOOL', 'SIZRFRI1', 'TYPERFR1', 'AGERFRI1', 'SIZRFRI2', 'TYPERFR2', 'AGERFRI2', 'NUMFREEZ', 'SIZFREEZ', 'AGEFRZR', 'STOVENFUEL', 'OVENUSE', 'AMTMICRO', 'DWASHUSE', 'WASHLOAD', 'WASHTEMP', 'EQUIPM', 'FUELHEAT', 'EQUIPAGE', 'PROTHERM', 'TEMPHOME', 'TEMPGONE', 'TEMPNITE', 'AGECENAC', 'USECENAC', 'NUMBERAC', 'WWACAGE', 'USEWWAC', 'FUELH2O', 'WHEATAGE', 'WHEATSIZ', 'LGTOUTNUM', 'ESDISHW', 'PGASHEAT', 'WOODAMT']

Duplicate Count : 0
shape of X is (21430, 79)

In [6]:
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
train_features, test_features, train_labels, test_labels = train_test_split(features_X, labels, test_size = 0.2, random_state = 30)

In [7]:
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)

Training Features Shape: (17144, 79)
Training Labels Shape: (17144,)
Testing Features Shape: (4286, 79)
Testing Labels Shape: (4286,)

In [15]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor

In [16]:
#Base model 
rf_base = RandomForestRegressor()

In [19]:
# Final Tuning(n_estimators)

# Instantiate model with 85 decision trees


rf = RandomForestRegressor(n_estimators =85, random_state = 30, max_depth = 11)

# Train the model on training data
rf.fit(train_features, train_labels);

In [20]:
from sklearn.metrics import mean_squared_error
predictions = rf.predict(test_features)
MSE = mean_squared_error(test_labels, predictions)

r2 = rf.score(test_features, test_labels)
print(MSE)
print(r2)

111694.66018128376
0.8239261064838361

In [10]:
# Random Forests in sklearn will automatically calculate feature importance
importances = rf.feature_importances_
#importances

In [15]:
# We can sort the features by their importance
df=pd.DataFrame(sorted(zip(rf.feature_importances_,columns_names), reverse=True))
print(df)

           0                 1
0   0.271704          TOTHSQFT
1   0.132180           WINDOWS
2   0.069923          CUFEETNG
3   0.042871          GALLONLP
4   0.041873          NHSLDMEM
5   0.040565          DIVISION
6   0.034861          TOTCSQFT
7   0.034249           REGIONC
8   0.032418      TVAUDIOEQUIP
9   0.028834             CDD65
10  0.024538          TOTROOMS
11  0.019837          BEDROOMS
12  0.018500             HDD65
13  0.016135           MONEYPY
14  0.010531          WASHLOAD
15  0.009345             HHAGE
16  0.009232          TOTUSQFT
17  0.008903          FUELHEAT
18  0.008684        PCOFFEQUIP
19  0.007767           NUMCFAN
20  0.005641          SIZRFRI2
21  0.005499          TEMPGONE
22  0.005454          SIZFREEZ
23  0.005306          TEMPNITE
24  0.005001          AMTMICRO
25  0.004624          DWASHUSE
26  0.004383          TEMPHOME
27  0.004293          TYPERFR2
28  0.004086          NCOMBATH
29  0.003779           OCCUPYY
..       ...               ...
42  0.002929         LGTOUTNUM
43  0.002708          WASHTEMP
44  0.002664          NUMBERAC
45  0.002637          NUMFREEZ
46  0.002491          AGECENAC
47  0.002439           FUELH2O
48  0.002355          SIZRFRI1
49  0.002339             PHONE
50  0.002320          WHEATSIZ
51  0.002207          PRKGPLC1
52  0.002184           RECBATH
53  0.001957           WOODAMT
54  0.001810            DRAFTY
55  0.001803           WWACAGE
56  0.001736          USECENAC
57  0.001728        STOVENFUEL
58  0.001583            CELLAR
59  0.001456          ADQINSUL
60  0.001416          EMPLOYHH
61  0.001292  HOUSEHOLDER_RACE
62  0.001259           USEWWAC
63  0.001212           STORIES
64  0.000993          NHAFBATH
65  0.000981           ESDISHW
66  0.000910          PROTHERM
67  0.000802             HHSEX
68  0.000752          PGASHEAT
69  0.000543          FUELPOOL
70  0.000457           ELECAUX
71  0.000358           LPWATER

[72 rows x 2 columns]

In [18]:
data_plot = raw_df[['BTUELOTH','WINDOWS', 'TOTHSQFT','CUFEETNG','BTUFO','BTUEL','REGIONC','GALLONLP','BTUELCOL','HDD65','BTUELRFG',"TOTALDOLLAR"]]

In [ ]:
fcols = 3
y_vars=['BTUELOTH','WINDOWS', 'TOTHSQFT','CUFEETNG','BTUFO','BTUEL','MONEYPY','GALLONLP','BTUELCOL','HDD65','BTUELRFG']
frows = ceil(len(y_vars)/fcols)
plt.figure(figsize=(15,4*frows))

for i,col in enumerate(y_vars):
    plt.subplot(frows,fcols,i+1)
    sns.violinplot(data_plot[col],data_plot['TOTALDOLLAR'])
#g.map(plt.scatter, alpha=0.5)
#g.add_legend();
#plt.savefig('C:/Users/admin/Desktop/Project3final/Pictures/RandomForestTotalDollar.png')

In [ ]:
#g = sns.pairplot(data_plot)
#g.map(plt.scatter, alpha=0.5)
#g.add_legend();
#plt.savefig('C:/Users/admin/Desktop/Project3final/Pictures/RandomForestTotalDollar.png')